# This file was based on ci.yml file, but is unmanaged by the sbt plugin
# and was edited manually. Should be removed when sangria-derivation will
# be merged for Scala 3

name: Continuous Integration (Scala 3)

on:
  pull_request:
    branches: ['**']
  push:
    branches: ['**']
    tags: [v*]

jobs:
  build:
    name: Build and Test on Scala 3
    strategy:
      matrix:
        os: [ubuntu-latest]
        scala: [3.1.3]
        java: [temurin@11]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout current branch (full)
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup Java (temurin@11)
        if: matrix.java == 'temurin@11'
        uses: actions/setup-java@v2
        with:
          distribution: temurin
          java-version: 11

      - name: Cache sbt
        uses: actions/cache@v2
        with:
          path: |
            ~/.sbt
            ~/.ivy2/cache
            ~/.coursier/cache/v1
            ~/.cache/coursier/v1
            ~/AppData/Local/Coursier/Cache/v1
            ~/Library/Caches/Coursier/v1
          key: ${{ runner.os }}-sbt-cache-v2-${{ hashFiles('**/*.sbt') }}-${{ hashFiles('project/build.properties') }}

      - name: Check binary compatibility
        run: sbt ++${{ matrix.scala }} "sangria-ast/mimaReportBinaryIssues;sangria-parser/mimaReportBinaryIssues;sangria-core/mimaReportBinaryIssues"

      - name: Check formatting
        run: sbt ++${{ matrix.scala }} scalafmtCheckAll

      - name: Build and test project
        run: sbt ++${{ matrix.scala }} "sangria-parser/test;sangria-core/test"